# Generated by Django 4.2 on 2023-06-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-date',), 'verbose_name': 'Products'},
        ),
    ]
